### ISSUE TITLE
FoldTextView第181行是不是写错了？

### ISSUE THREAD

**Issue by jessieeeee** [zzh12138/FoldText_Kotlin#1]
`  viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
                override fun onGlobalLayout() {
                    viewTreeObserver.removeOnGlobalLayoutListener(this)
                    translateText(l, type)
                }
            })`
` translateText(l, type)` 应该是 translateText(layout, type)

**Comment by zzh12138** [comment]
是的，已改
